/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include"stm32f411xx.h"
#include<stdio.h>
void GPIO_Configure()
{
	GPIO_Handle_t led;
	led.pGPIOx=GPIOC;
	led.GPIO_PinConfig.GPIO_PinNo=13;
	led.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
	led.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	led.GPIO_PinConfig.GPIO_pinOpType=GPIO_OPTYPE_PP;
	led.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_NO_PUPD;
	GPIO_PeriClockControl(GPIOC, ENABLE);
	GPIO_Init(&led);

	GPIO_Handle_t button;
	button.pGPIOx=GPIOA;
	button.GPIO_PinConfig.GPIO_PinNo=0;
	button.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IT_FT;
	button.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	button.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PU;
	button.GPIO_PinConfig.GPIO_pinOpType=GPIO_OPTYPE_PP;

	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&button);
	IRQ_InterruptConfig(6, ENABLE);
}

int main(void)
{
    /* Loop forever */
	printf("Start\n");
	GPIO_Configure();
	GPIO_WriteOutputPin(GPIOC, 13, 1);
	GPIO_WriteOutputPin(GPIOC, 13, 0);
	for(;;);

}

void EXTI0_IRQHandler()
{
	printf("In the interrupt\n");
	GPIO_ToggleOutputPin(GPIOC, 13);
	IRQ_Handle(0);
}
